---
title: "Penguin Analysis"
author: "Jiaying Liao"
date: "`r Sys.Date()`"
output: bookdown::html_document2
bibliography: citations.bib
csl: apa.csl
---
# Introduction

```{r setup, include=FALSE,warning=FALSE}

source(here::here("R/predict.R"))
library(palmerpenguins)
library(knitr)
library(tidyverse)
```

```{r working directory}
print(getwd())
```

# Methods

```{r echo=FALSE, message=FALSE, warning=FALSE}
head(penguins) %>% kable()
```

Add citation here [@bashir2014ensemble], and here [@Einstein1905].

## Model 1
```{r my-plot, message=FALSE, warning=FALSE,fig.cap="caption"}
#| message=FALSE,
#| warning=FALSE,
#| fig.alt="screen reader"

ggplot(penguins, aes(x=bill_length_mm, 
                     y=flipper_length_mm,
                     color=species)) +
  geom_point() +
  geom_hline(yintercept = 205)+
  geom_vline(xintercept = 45) + theme(panel.grid.major = element_line(colour = "lavenderblush3"),
    panel.grid.minor = element_line(colour = "lavenderblush2"),
    plot.title = element_text(face = "bold"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "darkgray")) +labs(title = "Penguins", x = "bill length (mm)",
    y = "flipper length (mm)", subtitle = "Body information",
    caption = "A penguin plot")
```

## Model 2

```{r echo=FALSE, message=FALSE, warning=FALSE}
# FIXME: fix me :(
penguins <- penguins %>%
  drop_na() %>% # TODO: clean up at the top
  mutate(my_predict = map2_chr(bill_length_mm, 
                               flipper_length_mm, 
                               classify_penguin))
```

```{r message=FALSE, warning=FALSE}
penguins %>%
  count(species, my_predict) %>%
  kable(col.names = c("Species", "My prediction","Number"))
```

# Result
<!--
TODO: this is an html comment
-->
Our data has `r nrow(penguins)` rows.

Figure \@ref(fig:my-plot) has shown something interesting.

# References

